[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Allow sendfox recaptcha to work cross-origin
[[headers]]
  for = "/signup/"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none'"

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/knowledge-share/"
  to = "/#interviews"
  status = 301

[[redirects]]
  from = "/knowledge-share"
  to = "/#interviews"
  status = 301
